In [1]:
import os
os.environ["OPENBLAS_NUM_THREADS"] = "1"
import warnings
warnings.filterwarnings("ignore")
import sys
sys.path.append('../..')

In [2]:
import numpy as np
from sklearn.cluster import SpectralClustering, AgglomerativeClustering, KMeans

In [3]:
from pygraphs.measure import *
from pygraphs.cluster import KernelKMeans
from pygraphs.graphs import Datasets

In [4]:
A = np.array([
    [0, 1, 1, 0, 0, 0, 0],
    [1, 0, 1, 0, 0, 0, 0],
    [1, 1, 0, 1, 0, 0, 0],
    [0, 0, 1, 0, 1, 1, 1],
    [0, 0, 0, 1, 0, 1, 1],
    [0, 0, 0, 1, 1, 0, 1],
    [0, 0, 0, 1, 1, 1, 0],
])

In [5]:
D_SP = SP_D(A).get_D(None)
D_SP

array([[0., 1., 1., 2., 3., 3., 3.],
       [1., 0., 1., 2., 3., 3., 3.],
       [1., 1., 0., 1., 2., 2., 2.],
       [2., 2., 1., 0., 1., 1., 1.],
       [3., 3., 2., 1., 0., 1., 1.],
       [3., 3., 2., 1., 1., 0., 1.],
       [3., 3., 2., 1., 1., 1., 0.]])

In [6]:
K_SP = SP_K(A).get_K(None)
K_SP

array([[ 1.08163265,  0.58163265,  0.29591837, -0.2755102 , -0.56122449,
        -0.56122449, -0.56122449],
       [ 0.58163265,  1.08163265,  0.29591837, -0.2755102 , -0.56122449,
        -0.56122449, -0.56122449],
       [ 0.29591837,  0.29591837,  0.51020408, -0.06122449, -0.34693878,
        -0.34693878, -0.34693878],
       [-0.2755102 , -0.2755102 , -0.06122449,  0.36734694,  0.08163265,
         0.08163265,  0.08163265],
       [-0.56122449, -0.56122449, -0.34693878,  0.08163265,  0.79591837,
         0.29591837,  0.29591837],
       [-0.56122449, -0.56122449, -0.34693878,  0.08163265,  0.29591837,
         0.79591837,  0.29591837],
       [-0.56122449, -0.56122449, -0.34693878,  0.08163265,  0.29591837,
         0.29591837,  0.79591837]])

In [7]:
a, info = Datasets()['news_2cl_1']
An, gtn = a[0]
Dn_SP = SP_D(An).get_D(None)
Kn_SP = SP_K(An).get_K(None)

In [8]:
OF = np.array([
    [1, 1, 0, 2],
    [1, 1, 1, 4],
    [0, 1, 1, 5]
])

In [9]:
kkm = KernelKMeans(n_clusters=2, kernel='precomputed', n_init=10, max_iter=300, tol=1e-4, verbose=1)
kkm.fit_predict(Kn_SP)

Converged at iteration 6
Initialization  0, inertia 493.993, ari 0.739
best inertia!
Converged at iteration 5
Initialization  1, inertia 492.247, ari 0.739
best inertia!
Converged at iteration 4
Initialization  2, inertia 493.577, ari 0.748
Converged at iteration 5
Initialization  3, inertia 494.335, ari 0.756
Converged at iteration 6
Initialization  4, inertia 492.839, ari 0.739
Converged at iteration 7
Initialization  5, inertia 494.335, ari 0.756
Converged at iteration 14
Initialization  6, inertia 566.933, ari 0.383
Converged at iteration 5
Initialization  7, inertia 493.107, ari 0.730
Converged at iteration 12
Initialization  8, inertia 493.107, ari 0.730
Converged at iteration 5
Initialization  9, inertia 493.561, ari 0.722
best inertia 492.24712033379546 ari 0.7389480899167746


array([1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [10]:
km = KMeans(n_clusters=2, verbose=1)
km.fit_predict(K_SP)

Initialization complete
start iteration
done sorting
end inner loop
Iteration 0, inertia 1.857142857142858
start iteration
done sorting
end inner loop
Iteration 1, inertia 1.857142857142858
center shift 0.000000e+00 within tolerance 2.253228e-05
Initialization complete
start iteration
done sorting
end inner loop
Iteration 0, inertia 1.857142857142858
start iteration
done sorting
end inner loop
Iteration 1, inertia 1.857142857142858
center shift 0.000000e+00 within tolerance 2.253228e-05
Initialization complete
start iteration
done sorting
end inner loop
Iteration 0, inertia 1.857142857142858
start iteration
done sorting
end inner loop
Iteration 1, inertia 1.857142857142858
center shift 0.000000e+00 within tolerance 2.253228e-05
Initialization complete
start iteration
done sorting
end inner loop
Iteration 0, inertia 1.857142857142858
start iteration
done sorting
end inner loop
Iteration 1, inertia 1.857142857142858
center shift 0.000000e+00 within tolerance 2.253228e-05
Initialization c

array([1, 1, 1, 0, 0, 0, 0], dtype=int32)

In [11]:
sc = SpectralClustering(n_clusters=2, affinity='precomputed')#, affinity=lambda x, y: 0.5 + K_SP[int(x[0]), int(y[0])])

In [12]:
sc.fit_predict(K_SP + 1)

array([1, 1, 1, 0, 0, 0, 0], dtype=int32)

In [13]:
sc.fit_predict([[x] for x in range(7)])

ValueError: array must be 2-dimensional and square. shape = (7, 1)

In [ ]:
sc.fit_predict(K_SP)

In [14]:
ac = AgglomerativeClustering(n_clusters=2, affinity='precomputed', linkage='complete')
ac.fit_predict(D_SP)

array([1, 1, 1, 0, 0, 0, 0])

In [18]:
ac.fit_predict(K_SP)

array([0, 1, 0, 0, 0, 1, 0])

In [ ]:
ac.fit_predict(OF)